// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-o7iwjRCEFwSZmOPjqF8stbUAhIkcPYc',
    appId: '1:904095169215:web:46be1483de461c91ade40a',
    messagingSenderId: '904095169215',
    projectId: 'prime-basis-441408-a6',
    authDomain: 'prime-basis-441408-a6.firebaseapp.com',
    storageBucket: 'prime-basis-441408-a6.firebasestorage.app',
    measurementId: 'G-5207799LGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlA4HgApAceX0g7fVBJB5uFBrQMqhqNw8',
    appId: '1:904095169215:android:8f511507c18f42c4ade40a',
    messagingSenderId: '904095169215',
    projectId: 'prime-basis-441408-a6',
    storageBucket: 'prime-basis-441408-a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9zFkwfvRDwSzHAWuKkLb6xBr3oJyurXQ',
    appId: '1:904095169215:ios:60ed47c2789077a2ade40a',
    messagingSenderId: '904095169215',
    projectId: 'prime-basis-441408-a6',
    storageBucket: 'prime-basis-441408-a6.firebasestorage.app',
    androidClientId: '904095169215-577qi8chucbn8a4kh6ip0565aqpfnd2m.apps.googleusercontent.com',
    iosClientId: '904095169215-j1if99imklni3qu397lv98e0ldka4dt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.walkfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9zFkwfvRDwSzHAWuKkLb6xBr3oJyurXQ',
    appId: '1:904095169215:ios:60ed47c2789077a2ade40a',
    messagingSenderId: '904095169215',
    projectId: 'prime-basis-441408-a6',
    storageBucket: 'prime-basis-441408-a6.firebasestorage.app',
    androidClientId: '904095169215-577qi8chucbn8a4kh6ip0565aqpfnd2m.apps.googleusercontent.com',
    iosClientId: '904095169215-j1if99imklni3qu397lv98e0ldka4dt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.walkfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-o7iwjRCEFwSZmOPjqF8stbUAhIkcPYc',
    appId: '1:904095169215:web:31b74edda75f8ef1ade40a',
    messagingSenderId: '904095169215',
    projectId: 'prime-basis-441408-a6',
    authDomain: 'prime-basis-441408-a6.firebaseapp.com',
    storageBucket: 'prime-basis-441408-a6.firebasestorage.app',
    measurementId: 'G-9K63SRBZB2',
  );
}
